### ISSUE TITLE
pgbackrest containers fail after in-place major version upgrade

### ISSUE THREAD

**Issue by rocket357** [cybertec-postgresql/CYBERTEC-pg-operator#52]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** docker.io/cybertecpostgresql/cybertec-pg-operator-dev:v0.7.0-2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** GKE
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug Report

While functional testing postgres-operator on GKE, I noticed that pgbasebackup jobs fail after a major version upgrade (they were working prior to upgrade).  They fail with the following messages in the logs:

```
Fri Jul 26 16:00:30 UTC 2024 INFO: Start pgBackRest-PreCondition-Check
Fri Jul 26 16:00:30 UTC 2024 INFO: pgBackRest: Backup-Job found
Fri Jul 26 16:00:30 UTC 2024 INFO: pgBackRest: Detect Primary-Pod jjsisson-test-major-upgrade-1 
WARN: configuration file contains invalid option 'repo1-gcs-region'
ERROR: [051]: PostgreSQL version 16, system-id 7395965093018820818 do not match stanza version 15, system-id 7395960876414242887
       HINT: is this the correct stanza?
command terminated with exit code 51
Fri Jul 26 16:00:31 UTC 2024 ERROR: pgBackRest: Create basebackup failed
```

It looks like the pgbackrest `stanza-upgrade` command needs to be run after a major version upgrade.  Is that something the operator can handle, or perhaps scripted into the pgbackrest image?

**Comment by Schmaetz** [comment]
is fixed by https://github.com/cybertec-postgresql/CYBERTEC-pg-container/pull/47
